services:
  bot:
    build:
      context: ./bot
    container_name: where_is_typhoon_bot
    env_file:
      - ./bot/.env
    depends_on:
      genmap:
        condition: service_healthy
    restart: unless-stopped

  genmap:
    build:
      context: ./genmap
    container_name: where_is_typhoon_genmap
    env_file:
      - ./genmap/.env
    healthcheck:
      test: "curl -fs http://127.0.0.1:8080/health"
      start_period: 2s
      interval: 3s
      timeout: 1s
      retries: 3
    restart: unless-stopped
