services:
  bot:
    build:
      context: ./bot
    container_name: where_is_typhoon_bot
    env_file:
      - ./bot/.env
    restart: unless-stopped

  genmap:
    build:
      context: ./genmap
    container_name: where_is_typhoon_genmap
    env_file:
      - ./genmap/.env
    restart: unless-stopped
